version: 2
updates:
  # Check for updates to npm packages
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      dev-dependencies:
        patterns:
          - "*eslint*"
          - "*prettier*"
          - "@types/*"
          - "typescript*"
      production-dependencies:
        patterns:
          - "react*"
          - "*react*"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "dependabot"

  # Check for updates to GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "dependabot"
